### ISSUE TITLE
bug screen

### ISSUE THREAD

**Issue by THZoria** [Murasaki64/PoyoTools#1]
![bug](https://user-images.githubusercontent.com/50277488/67836469-fd469d00-faec-11e9-9421-10404c545ade.PNG)

**Comment by Murasaki64** [comment]
Merci pour m'avoir notifié de ce bug ^^

**Comment by Murasaki64** [comment]
La version 1.0.0 est patch. Vous pouvez me recontacter si besoin. Le sujet "Bug Screen" est clos.
